# question a
FROM node:14

# question b
WORKDIR /app

# question c
COPY package.json .
# question d
RUN npm install

# question e
COPY . .

# question f
EXPOSE 3010

# question g
CMD ["node", "server.js"]
